version: '3'

services:
        srv:
            image: node
            working_dir: /app
            command: sh -c "cd project-veterinaire && npm run start:dev"
            volumes:
                    - $PWD:/app
            ports:
                    - 3000:3000        
            links:
                  - bdd
        bdd:
            image: postgres:alpine
            environment:
                  - POSTGRES_PASSWORD=secret